# Generated by Django 5.2.6 on 2025-10-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Computadoras', 'Computadoras'), ('Notebook', 'Notebook'), ('Impresoras', 'Impresoras'), ('Almacenamiento', 'Almacenamiento'), ('Conectividad', 'Conectividad'), ('Componentes de PC', 'Componentes de PC'), ('Periféricos', 'Periféricos'), ('Insumos', 'Insumos'), ('Gaming', 'Gaming')], default=1, help_text='Selecciona la categoría del menú donde aparecerá este producto', max_length=100),
            preserve_default=False,
        ),
    ]
