# Generated by Django 5.2.6 on 2025-10-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del producto (ej: Logitech, HP, Samsung)', max_length=50, null=True),
        ),
    ]
