# Generated by Django 5.2.6 on 2025-10-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('PC Armada', 'PC Armada'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('HP', 'HP'), ('Computadoras', 'Computadoras'), ('Notebook', 'Notebook'), ('Impresoras', 'Impresoras'), ('Almacenamiento', 'Almacenamiento'), ('Conectividad', 'Conectividad'), ('Componentes de PC', 'Componentes de PC'), ('Periféricos', 'Periféricos'), ('Insumos', 'Insumos'), ('Gaming', 'Gaming')], help_text='Selecciona la categoría del menú donde aparecerá este producto', max_length=100),
        ),
    ]
