# Generated by Django 5.2.6 on 2025-10-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('PC Armada', 'PC Armada'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('HP', 'HP'), ('Dell', 'Dell'), ('Laser', 'Laser'), ('Multifunción', 'Multifunción'), ('Matricial', 'Matricial'), ('SSD', 'SSD'), ('Disco Duro', 'Disco Duro'), ('Pendrive', 'Pendrive'), ('Tarjeta SD', 'Tarjeta SD'), ('Discos Externos', 'Discos Externos'), ('Router', 'Router'), ('Switch', 'Switch'), ('Extensores WiFi', 'Extensores WiFi'), ('USB WiFi', 'USB WiFi'), ('PCI WiFi', 'PCI WiFi'), ('Procesadores', 'Procesadores'), ('Motherboards', 'Motherboards'), ('Memorias RAM', 'Memorias RAM'), ('Placas de Video', 'Placas de Video'), ('Gabinetes', 'Gabinetes'), ('Fuentes', 'Fuentes'), ('Coolers', 'Coolers'), ('Mouse', 'Mouse'), ('Teclados', 'Teclados'), ('Auriculares', 'Auriculares'), ('Webcam', 'Webcam'), ('Parlantes', 'Parlantes'), ('Micrófonos', 'Micrófonos'), ('Cartuchos', 'Cartuchos'), ('Tóners', 'Tóners'), ('Tintas', 'Tintas'), ('Mouse Gamer', 'Mouse Gamer'), ('Teclados Gamer', 'Teclados Gamer'), ('Auriculares Gamer', 'Auriculares Gamer'), ('Computadoras', 'Computadoras'), ('Notebook', 'Notebook'), ('Impresoras', 'Impresoras'), ('Almacenamiento', 'Almacenamiento'), ('Conectividad', 'Conectividad'), ('Componentes de PC', 'Componentes de PC'), ('Periféricos', 'Periféricos'), ('Insumos', 'Insumos'), ('Gaming', 'Gaming')], help_text='Selecciona la categoría del menú donde aparecerá este producto', max_length=100),
        ),
    ]
