# Generated by Django 5.2.6 on 2025-11-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alimentacion',
            field=models.CharField(blank=True, help_text='Tipo de alimentación (ej: 1 pila AA, batería recargable, cable USB)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Características principales (una por línea)', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='compatibilidad',
            field=models.TextField(blank=True, help_text='Sistemas operativos o dispositivos compatibles', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='conectividad',
            field=models.CharField(blank=True, help_text='Tipo de conexión (ej: Wireless 2.4GHz, Bluetooth, USB)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='especificaciones_tecnicas',
            field=models.TextField(blank=True, help_text='Especificaciones técnicas detalladas (ej: procesador, RAM, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='garantia',
            field=models.CharField(blank=True, help_text='Tiempo de garantía (ej: 12 meses, 2 años)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo o número de parte (ej: M170, ProBook 450)', max_length=100, null=True),
        ),
    ]
